baseurl = "/"
title = "University of Colorado Molecular Biology Program"
languageCode = "en-us"
paginate = "12" # Number of posts per page
theme = "Mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-121846153-1" # Enable Google Analytics by entering your tracking id
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Author]
    name = "Jay Hesselberth"
    bio = "Yep."
    avatar = "img/people/hesselberth.png"


[Params]
    subtitle = "Just another site" # Subtitle of your site
    description = "University of Colorado Molecular Biology Program" # Description of your site
    opengraph = true
    twitter_cards = true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = false
    post_navigation = true
    postSections = ["post"]


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
    social_twitter = "molbcu"